package ru.tech.kastybiy.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006e11)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF7dfd7a)
val md_theme_light_onPrimaryContainer = Color(0xFF002202)
val md_theme_light_secondary = Color(0xFF2d6b27)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFaff49f)
val md_theme_light_onSecondaryContainer = Color(0xFF002200)
val md_theme_light_tertiary = Color(0xFF8d4f00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdcbc)
val md_theme_light_onTertiaryContainer = Color(0xFF2d1600)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFF61e061)

val md_theme_dark_primary = Color(0xFF61e061)
val md_theme_dark_onPrimary = Color(0xFF003a04)
val md_theme_dark_primaryContainer = Color(0xFF00530a)
val md_theme_dark_onPrimaryContainer = Color(0xFF7dfd7a)
val md_theme_dark_secondary = Color(0xFF94d786)
val md_theme_dark_onSecondary = Color(0xFF003a00)
val md_theme_dark_secondaryContainer = Color(0xFF125211)
val md_theme_dark_onSecondaryContainer = Color(0xFFaff49f)
val md_theme_dark_tertiary = Color(0xFFffb871)
val md_theme_dark_onTertiary = Color(0xFF4b2700)
val md_theme_dark_tertiaryContainer = Color(0xFF6c3b00)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdcbc)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF006e11)